/* =========================================================
   AutoHub — Mock Data Layer
   All data is static/mock for the MVP prototype.
   ========================================================= */

// ---- Quick Services (Home grid) ----
const QUICK_SERVICES = [
  { id: 'sos',      label: 'SOS Emergency', icon: 'sos',      accent: 'danger', category: 'Emergency' },
  { id: 'mechanic', label: 'Mechanic',      icon: 'wrench',   accent: 'blue',   category: 'Mechanic' },
  { id: 'towing',   label: 'Towing',        icon: 'tow',      accent: 'orange', category: 'Towing' },
  { id: 'battery',  label: 'Battery',       icon: 'battery',  accent: 'blue',   category: 'Battery' },
  { id: 'tire',     label: 'Tire Service',  icon: 'tire',     accent: 'orange', category: 'Tire' },
  { id: 'oil',      label: 'Oil Change',    icon: 'oil',      accent: 'blue',   category: 'Oil Change' },
  { id: 'ac',       label: 'AC Service',    icon: 'ac',       accent: 'orange', category: 'AC Service' },
  { id: 'wash',     label: 'Car Wash',      icon: 'wash',     accent: 'blue',   category: 'Car Wash' },
  { id: 'fuelstation', label: 'Fuel Station', icon: 'fuel',  accent: 'orange', category: 'Fuel Station' },
  { id: 'evstation',   label: 'EV Station',   icon: 'battery', accent: 'blue',  category: 'EV Station' },
];

// ---- Emergency options (SOS screen) ----
const EMERGENCY_OPTIONS = [
  { id: 'tow',     label: 'Tow Truck',          icon: 'tow',     desc: 'Vehicle pickup & transport', eta: '12 min' },
  { id: 'jump',    label: 'Battery Jump Start',  icon: 'battery', desc: 'Dead battery boost on-site', eta: '9 min'  },
  { id: 'flat',    label: 'Flat Tire',           icon: 'tire',    desc: 'Tire change or repair',      eta: '15 min' },
  { id: 'fuel',    label: 'Fuel Delivery',       icon: 'oil',     desc: 'Emergency fuel to you',      eta: '18 min' },
  { id: 'mech',    label: 'Emergency Mechanic',  icon: 'wrench',  desc: 'Roadside diagnostics',       eta: '14 min' },
];

// ---- Service Providers (10 in Phnom Penh) ----
const PROVIDERS = [
  {
    id: 'autohub-partner',
    name: 'AutoHub Partner Garage',
    category: 'Mechanic',
    tags: ['Full Service', 'Diagnostics', 'Engine'],
    rating: 4.9,
    reviews: 412,
    distance: 1.2,
    eta: '8 min',
    address: 'St. 271, Toul Tom Poung, Phnom Penh',
    lat: 11.5478, lng: 104.9182,
    phone: '+855 23 900 100',
    open: true,
    hours: 'Mon–Sun · 7:00 AM – 8:00 PM',
    mobile: true,
    emergency: true,
    open24: false,
    featured: true,
    color1: '#ff7a18', color2: '#2b1502',
    services: ['Engine Repair', 'Diagnostics', 'Brake Service', 'Suspension', 'Electrical'],
    description: 'AutoHub flagship partner garage offering complete vehicle care with certified technicians, genuine parts, and transparent pricing. Trusted by thousands of drivers across Phnom Penh.',
  },
  {
    id: 'premium-auto-care',
    name: 'Premium Auto Care',
    category: 'Detailing',
    tags: ['Detailing', 'Service', 'Premium'],
    rating: 4.8,
    reviews: 327,
    distance: 2.0,
    eta: '11 min',
    address: 'Norodom Blvd, Chamkarmon, Phnom Penh',
    lat: 11.5533, lng: 104.9270,
    phone: '+855 23 900 200',
    open: true,
    hours: 'Mon–Sat · 8:00 AM – 7:00 PM',
    mobile: false,
    emergency: false,
    open24: false,
    featured: true,
    color1: '#ff7a18', color2: '#3a1602',
    services: ['Full Detailing', 'Paint Protection', 'Periodic Service', 'Interior Care'],
    description: 'A premium auto care studio specialising in detailing and scheduled servicing. White-glove treatment for your vehicle with imported products and skilled detailers.',
  },
  {
    id: 'pp-towing',
    name: 'Phnom Penh Towing Service',
    category: 'Towing',
    tags: ['Towing', '24/7', 'Recovery'],
    rating: 4.7,
    reviews: 198,
    distance: 0.9,
    eta: '6 min',
    address: 'Russian Blvd, Toul Kork, Phnom Penh',
    lat: 11.5865, lng: 104.8951,
    phone: '+855 23 900 300',
    open: true,
    hours: 'Open 24 hours',
    mobile: true,
    emergency: true,
    open24: true,
    featured: false,
    color1: '#ff7a18', color2: '#2b1502',
    services: ['Flatbed Towing', 'Accident Recovery', 'Long Distance Tow', 'Winching'],
    description: 'Round-the-clock towing and recovery across Phnom Penh and provinces. Fast dispatch, flatbed trucks, and careful handling for all vehicle types.',
  },
  {
    id: 'battery-express',
    name: 'Battery Express',
    category: 'Battery',
    tags: ['Battery', 'Mobile Service', 'Jump Start'],
    rating: 4.6,
    reviews: 256,
    distance: 1.6,
    eta: '10 min',
    address: 'St. 217, Tuol Sangke, Phnom Penh',
    lat: 11.6041, lng: 104.8847,
    phone: '+855 23 900 400',
    open: true,
    hours: 'Mon–Sun · 6:00 AM – 9:00 PM',
    mobile: true,
    emergency: true,
    open24: false,
    featured: false,
    color1: '#1f6feb', color2: '#0b2a52',
    services: ['Battery Replacement', 'Jump Start', 'Battery Testing', 'Mobile Install'],
    description: 'Specialists in vehicle batteries with on-site replacement and jump-start service. Stocks major brands and offers warranty on every battery installed.',
  },
  {
    id: 'tire-pro',
    name: 'Tire Pro Cambodia',
    category: 'Tire',
    tags: ['Tire', 'Alignment', 'Balancing'],
    rating: 4.7,
    reviews: 289,
    distance: 2.4,
    eta: '13 min',
    address: 'Mao Tse Toung Blvd, Phnom Penh',
    lat: 11.5605, lng: 104.9047,
    phone: '+855 23 900 500',
    open: true,
    hours: 'Mon–Sat · 7:30 AM – 7:00 PM',
    mobile: false,
    emergency: false,
    open24: false,
    featured: false,
    color1: '#ff7a18', color2: '#2b1502',
    services: ['Tire Replacement', 'Wheel Alignment', 'Balancing', 'Puncture Repair'],
    description: 'A complete tire center stocking premium and economy brands. Computerised alignment and balancing keep your ride smooth and safe.',
  },
  {
    id: 'ac-auto',
    name: 'AC Auto Service',
    category: 'AC Service',
    tags: ['AC Repair', 'Cooling', 'Gas Refill'],
    rating: 4.5,
    reviews: 174,
    distance: 3.1,
    eta: '16 min',
    address: 'St. 360, Boeung Keng Kang, Phnom Penh',
    lat: 11.5475, lng: 104.9225,
    phone: '+855 23 900 600',
    open: false,
    hours: 'Mon–Sat · 8:00 AM – 6:00 PM',
    mobile: false,
    emergency: false,
    open24: false,
    featured: false,
    color1: '#1f6feb', color2: '#0b2a52',
    services: ['AC Repair', 'Gas Refill', 'Compressor Service', 'Cooling Diagnostics'],
    description: 'Dedicated automotive air-conditioning experts. From weak cooling to full compressor rebuilds, they keep your cabin comfortable in any heat.',
  },
  {
    id: 'japan-auto',
    name: 'Japan Auto Care',
    category: 'Mechanic',
    tags: ['Japanese Cars', 'Service', 'Parts'],
    rating: 4.8,
    reviews: 365,
    distance: 1.8,
    eta: '11 min',
    address: 'St. 271, Tuol Tumpung, Phnom Penh',
    lat: 11.5465, lng: 104.9195,
    phone: '+855 23 900 700',
    open: true,
    hours: 'Mon–Sun · 7:00 AM – 7:30 PM',
    mobile: false,
    emergency: false,
    open24: false,
    featured: true,
    color1: '#ff7a18', color2: '#2b1502',
    services: ['Toyota & Honda', 'Periodic Service', 'Genuine Parts', 'Engine Tune-up'],
    description: 'Japanese-vehicle specialists with deep expertise in Toyota, Honda, Lexus and Nissan. Genuine parts and factory-grade servicing.',
  },
  {
    id: 'hybrid-specialist',
    name: 'Hybrid Specialist Garage',
    category: 'Mechanic',
    tags: ['Hybrid', 'EV', 'Battery'],
    rating: 4.9,
    reviews: 142,
    distance: 2.9,
    eta: '15 min',
    address: 'St. 598, Chrang Chamres, Phnom Penh',
    lat: 11.6098, lng: 104.8995,
    phone: '+855 23 900 800',
    open: true,
    hours: 'Mon–Sat · 8:00 AM – 6:30 PM',
    mobile: false,
    emergency: false,
    open24: false,
    featured: true,
    color1: '#1f6feb', color2: '#0b2a52',
    services: ['Hybrid Battery', 'EV Diagnostics', 'Inverter Repair', 'High-Voltage Service'],
    description: 'The go-to garage for hybrid and electric vehicles. Specialised tools and trained technicians for high-voltage systems and hybrid battery health.',
  },
  {
    id: 'car-wash-plus',
    name: 'Car Wash Plus',
    category: 'Car Wash',
    tags: ['Car Wash', 'Detailing', 'Wax'],
    rating: 4.6,
    reviews: 521,
    distance: 0.7,
    eta: '5 min',
    address: 'St. 105, Phsar Daeum Thkov, Phnom Penh',
    lat: 11.5352, lng: 104.9148,
    phone: '+855 23 900 900',
    open: true,
    hours: 'Mon–Sun · 6:30 AM – 8:30 PM',
    mobile: false,
    emergency: false,
    open24: false,
    featured: false,
    color1: '#ff7a18', color2: '#2b1502',
    services: ['Exterior Wash', 'Interior Cleaning', 'Wax & Polish', 'Engine Bay Wash'],
    description: 'Fast, friendly car wash with express and premium packages. Steam cleaning, hand wax, and interior shampoo to make your car shine.',
  },
  {
    id: 'mobile-mechanic',
    name: 'Mobile Mechanic 24/7',
    category: 'Mechanic',
    tags: ['Mobile Service', '24/7', 'Roadside'],
    rating: 4.8,
    reviews: 233,
    distance: 1.1,
    eta: '7 min',
    address: 'Citywide · Phnom Penh',
    lat: 11.5564, lng: 104.9282,
    phone: '+855 23 901 000',
    open: true,
    hours: 'Open 24 hours',
    mobile: true,
    emergency: true,
    open24: true,
    featured: true,
    color1: '#ff7a18', color2: '#2b1502',
    services: ['Roadside Repair', 'On-site Diagnostics', 'Emergency Fix', 'Battery & Tire'],
    description: 'A fully mobile mechanic that comes to you anywhere in Phnom Penh, any time of day. Equipped van, fast response, and fair on-the-spot pricing.',
  },
  {
    id: 'total-station',
    name: 'TotalEnergies Station',
    category: 'Fuel Station',
    tags: ['Petrol', 'Diesel', 'Mini-mart'],
    rating: 4.5,
    reviews: 312,
    distance: 0.8,
    eta: '5 min',
    address: 'Monivong Blvd, Phnom Penh',
    lat: 11.5699, lng: 104.9198,
    phone: '+855 23 880 100',
    open: true,
    hours: 'Open 24 hours',
    mobile: false,
    emergency: false,
    open24: true,
    featured: false,
    color1: '#ff7a18', color2: '#2b1502',
    services: ['Petrol (Unleaded)', 'Diesel', 'Mini-mart', 'Air & Water'],
    description: 'A 24-hour fuel station with quality petrol and diesel, a convenience mini-mart, and free air & water for your tires.',
  },
  {
    id: 'caltex-station',
    name: 'Caltex Star Mart',
    category: 'Fuel Station',
    tags: ['Petrol', 'Car Wash', 'Cafe'],
    rating: 4.4,
    reviews: 198,
    distance: 1.5,
    eta: '9 min',
    address: 'Russian Blvd, Phnom Penh',
    lat: 11.5798, lng: 104.8977,
    phone: '+855 23 880 200',
    open: true,
    hours: 'Open 24 hours',
    mobile: false,
    emergency: false,
    open24: true,
    featured: false,
    color1: '#ff7a18', color2: '#2b1502',
    services: ['Petrol', 'Diesel', 'Express Car Wash', 'Star Mart', 'Cafe'],
    description: 'Full-service fuel station with Star Mart convenience store, an on-site cafe, and an express car wash.',
  },
  {
    id: 'ev-one',
    name: 'EV One Charging Hub',
    category: 'EV Station',
    tags: ['Fast Charge', 'CCS2', '24/7'],
    rating: 4.8,
    reviews: 142,
    distance: 1.1,
    eta: '7 min',
    address: 'Koh Pich, Phnom Penh',
    lat: 11.5448, lng: 104.9352,
    phone: '+855 23 881 100',
    open: true,
    hours: 'Open 24 hours',
    mobile: false,
    emergency: false,
    open24: true,
    featured: true,
    color1: '#1faf6a', color2: '#06351f',
    services: ['DC Fast Charge', 'CCS2 & CHAdeMO', 'Type 2 AC', 'Lounge'],
    description: 'A modern EV charging hub with high-speed DC fast chargers, multiple connector types, and a comfortable waiting lounge.',
  },
  {
    id: 'green-charge',
    name: 'GreenCharge EV Station',
    category: 'EV Station',
    tags: ['Type 2', 'Solar', 'App Pay'],
    rating: 4.6,
    reviews: 88,
    distance: 2.2,
    eta: '12 min',
    address: 'Toul Kork, Phnom Penh',
    lat: 11.5902, lng: 104.8898,
    phone: '+855 23 881 200',
    open: true,
    hours: 'Mon–Sun · 6:00 AM – 10:00 PM',
    mobile: false,
    emergency: false,
    open24: false,
    featured: false,
    color1: '#1faf6a', color2: '#06351f',
    services: ['Type 2 AC Charge', 'Solar-powered', 'App Payment'],
    description: 'An eco-friendly, solar-assisted EV charging station with convenient app-based payment and reliable AC charging.',
  },
];

// ---- Reviews (shared mock) ----
const REVIEWS = [
  { name: 'Sokha P.',   rating: 5, date: '2 days ago',  text: 'Super fast response and very professional. Fixed my issue on the spot. Highly recommend!' },
  { name: 'Dara K.',    rating: 5, date: '1 week ago',  text: 'Honest pricing and skilled mechanics. My car runs like new. Will come back for sure.' },
  { name: 'Lina S.',    rating: 4, date: '2 weeks ago', text: 'Good service overall, a little busy but worth the wait. Staff were friendly and helpful.' },
  { name: 'Vibol T.',   rating: 5, date: '3 weeks ago', text: 'Came to my location within 10 minutes during an emergency. Lifesavers!' },
];

// ---- Activity / History (mock) ----
const ACTIVITY = {
  recentlyViewed: ['mobile-mechanic', 'pp-towing', 'tire-pro', 'japan-auto'],
  recentCalls: [
    { id: 'pp-towing',        time: 'Today · 2:14 PM' },
    { id: 'battery-express',  time: 'Yesterday · 9:02 AM' },
  ],
  pastRequests: [
    { id: 'autohub-partner', service: 'Brake Service',   status: 'Completed', date: 'Jun 12, 2026' },
    { id: 'car-wash-plus',   service: 'Premium Wash',    status: 'Completed', date: 'Jun 05, 2026' },
    { id: 'ac-auto',         service: 'AC Gas Refill',   status: 'Cancelled', date: 'May 28, 2026' },
  ],
};

// ---- Explore promotions (mock) ----
const PROMOTIONS = [
  { id: 'p1', title: '20% Off First Service', sub: 'AutoHub Partner Garage', color1: '#1f6feb', color2: '#0b2a52', tag: 'Limited' },
  { id: 'p2', title: 'Free Battery Check',     sub: 'Battery Express',         color1: '#ff7a18', color2: '#2b1502', tag: 'This week' },
  { id: 'p3', title: 'Premium Wash + Wax',     sub: 'Car Wash Plus',           color1: '#1f6feb', color2: '#0b2a52', tag: 'Combo' },
];

// ---- Default favorites (mock starting state) ----
const DEFAULT_FAVORITES = ['mobile-mechanic', 'japan-auto'];

// ---- Nearby places (location picker) ----
const PLACES = [
  { label: 'St. 271, Toul Tom Poung', sub: 'Chamkarmon, Phnom Penh', lat: 11.5478, lng: 104.9182 },
  { label: 'Monivong Blvd', sub: 'Daun Penh, Phnom Penh', lat: 11.5699, lng: 104.9198 },
  { label: 'AEON Mall Sen Sok', sub: 'Sen Sok, Phnom Penh', lat: 11.5900, lng: 104.8700 },
  { label: 'Russian Blvd', sub: 'Toul Kork, Phnom Penh', lat: 11.5798, lng: 104.8977 },
];

// ---- Google Maps custom dark style (matches the app's night-map theme) ----
const DARK_MAP_STYLE = [
  { elementType: 'geometry', stylers: [{ color: '#1c2230' }] },
  { elementType: 'labels.text.stroke', stylers: [{ color: '#1c2230' }] },
  { elementType: 'labels.text.fill', stylers: [{ color: '#aeb6c6' }] },
  { featureType: 'administrative', elementType: 'geometry', stylers: [{ color: '#3a4256' }] },
  { featureType: 'poi', stylers: [{ visibility: 'off' }] },
  { featureType: 'road', elementType: 'geometry', stylers: [{ color: '#262d3d' }] },
  { featureType: 'road', elementType: 'labels.text.fill', stylers: [{ color: '#8b94a6' }] },
  { featureType: 'road.highway', elementType: 'geometry', stylers: [{ color: '#2f3850' }] },
  { featureType: 'transit', stylers: [{ visibility: 'off' }] },
  { featureType: 'water', elementType: 'geometry', stylers: [{ color: '#0c121d' }] },
];

// ---- Vehicle types (quick booking) ----
const VEHICLE_TYPES = [
  { id: 'car',     label: 'Car',     icon: 'car' },
  { id: 'bike',    label: 'Bike',    icon: 'wrench' },
  { id: 'scooter', label: 'Scooter', icon: 'wrench' },
  { id: 'bus',     label: 'Bus',     icon: 'car' },
  { id: 'truck',   label: 'Truck',   icon: 'tow' },
];

// ---- Booking time slots (hourly, skips the lunch hour) ----
const TIME_SLOTS = [
  '8:00 AM – 9:00 AM', '9:00 AM – 10:00 AM', '10:00 AM – 11:00 AM', '11:00 AM – 12:00 PM',
  '1:00 PM – 2:00 PM', '2:00 PM – 3:00 PM', '3:00 PM – 4:00 PM', '4:00 PM – 5:00 PM', '5:00 PM – 6:00 PM',
];

// ---- Registered vehicles (mock starting state) ----
const DEFAULT_VEHICLES = [
  { id: 'v1', type: 'car',  name: 'Toyota Highlander', plate: '2AB-1234', fuel: 'hybrid' },
  { id: 'v2', type: 'bike', name: 'Yamaha MT-07',      plate: '2BX-7877', fuel: 'petrol' },
];

// ---- Bookings (mock starting state; statuses: Confirmed / Completed / Cancelled) ----
const DEFAULT_BOOKINGS = [
  { id: 'b1', providerId: 'autohub-partner', vehicleId: 'v1', status: 'Confirmed',
    service: 'Brake Service',  date: 'Jun 25, 2026', time: '10:00 AM – 12:30 PM',
    location: 'St. 271, Toul Tom Poung, Phnom Penh' },
  { id: 'b2', providerId: 'premium-auto-care', vehicleId: 'v1', status: 'Completed',
    service: 'Full Detailing', date: 'Jun 12, 2026', time: '09:00 AM – 11:00 AM',
    location: 'Norodom Blvd, Chamkarmon, Phnom Penh' },
  { id: 'b3', providerId: 'ac-auto', vehicleId: 'v2', status: 'Cancelled',
    service: 'AC Gas Refill',  date: 'May 28, 2026', time: '02:00 PM – 03:00 PM',
    location: 'St. 360, Boeung Keng Kang, Phnom Penh' },
];

// ---- Notifications (mock starting state) ----
const DEFAULT_NOTIFICATIONS = [
  { id: 'n1', icon: 'check',  titleKey: 'ntf.n1.t', descKey: 'ntf.n1.d', timeKey: 'ntf.time.10m', read: false },
  { id: 'n2', icon: 'nav',    titleKey: 'ntf.n2.t', descKey: 'ntf.n2.d', timeKey: 'ntf.time.1h',  read: false },
  { id: 'n3', icon: 'fire',   titleKey: 'ntf.n3.t', descKey: 'ntf.n3.d', timeKey: 'ntf.time.3h',  read: true },
  { id: 'n4', icon: 'wrench', titleKey: 'ntf.n4.t', descKey: 'ntf.n4.d', timeKey: 'ntf.time.1d',  read: true },
  { id: 'n5', icon: 'star',   titleKey: 'ntf.n5.t', descKey: 'ntf.n5.d', timeKey: 'ntf.time.2d',  read: true },
];

// ---- Saved locations (mock starting state) ----
const DEFAULT_SAVED_LOCATIONS = [
  { id: 'sl1', icon: 'home',  labelKey: 'loc.home',  address: 'St. 271, Toul Tom Poung, Phnom Penh' },
  { id: 'sl2', icon: 'store', labelKey: 'loc.work',  address: 'Monivong Blvd, Daun Penh, Phnom Penh' },
  { id: 'sl3', icon: 'pin',   labelKey: 'loc.other', address: 'AEON Mall Sen Sok, Sen Sok, Phnom Penh' },
];

// ---- Helpers ----
function getProvider(id) { return PROVIDERS.find(p => p.id === id); }
function providersByCategory(cat) {
  if (cat === 'Emergency') return PROVIDERS.filter(p => p.emergency);
  return PROVIDERS.filter(p => p.category === cat);
}
